name = "github-release-version"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "c968f0981c8be250fe9f7fe046fa4311"
zone_id = "d481794b5b50a1d9d00b1a862bd28594"
vars = { CACHE_TIME = "60" }
routes = [ "mod.jpwilliams.dev/github-release-version*" ]
